module.exports = {
  products: [
    {
      id: 0,
      title: "Charmant appartement Strasbourg Centre",
      description: "Lorem ipsum dolor sit amet",
      img: "https://picsum.photos/500/400",
      slug: "charmant-appartement-strasbourg-centre",
      lat: 4.5436,
      lng: 12.352,
    },
    {
      id: 1,
      title: "Charmant appartement Strasbourg Meinau",
      description: "Lorem ipsum dolor sit amet",
      img: "https://picsum.photos/500/400",
      slug: "charmant-appartement-strasbourg-meinau",
      lat: 4.5436,
      lng: 12.352,
    },
    {
      id: 2,
      title: "Charmant appartement Strasbourg Est",
      description: "Lorem ipsum dolor sit amet",
      img: "https://picsum.photos/500/400",
      slug: "charmant-appartement-strasbourg-est",
      lat: 4.5436,
      lng: 12.352,
    },
    {
      id: 3,
      title: "Charmant appartement Rosheim",
      description: "Lorem ipsum dolor sit amet",
      img: "https://picsum.photos/500/400",
      slug: "charmant-appartement-rosheim",
      lat: 4.5436,
      lng: 12.352,
    },
  ],
}
